[package]
name = "agama-dbus-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agama-locale-data = { path="../agama-locale-data" }
zbus = "3.7.0"
async-std = { version = "1.12.0", features = ["attributes"]}